### ISSUE TITLE
1.7.3 now breaking when pulled

### ISSUE THREAD

**Issue by jonathanstiansen** [bitwalker/alpine-elixir-phoenix#47]
First of all, thanks **so** much for everything you do. I really appreciate everything you've created and helped the community with.

I'm pulling 1.7.3 on a new computer but it's getting this error:

```
== Compilation error in file lib/regen_web/views/page_view.ex ==
** (FunctionClauseError) no function clause matching in :elixir_erl_var.translate/4    
    
    The following arguments were given to :elixir_erl_var.translate/4:
    
        # 1
        [counter: {RegenWeb.Gettext, 9}, line: 2]
    
        # 2
        :msgid
    
        # 3
        {RegenWeb.Gettext, 9}
    
        # 4
        {:elixir_erl, :match, nil, false, %{{:assigns, nil} => {1, :_assigns@1}, {:tmp1, Phoenix.HTML.Engine} => {1, :__@1}}, %{{:assigns, nil} => {1, :_assigns@1}, {:tmp1, Phoenix.HTML.Engine} => {1, :__@1}}, [], %{_: 1, assigns: 1}, false}
    
    (elixir) src/elixir_erl_var.erl:10: :elixir_erl_var.translate/4
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
    (stdlib) lists.erl:1355: :lists.mapfoldl/3
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
    (stdlib) lists.erl:1355: :lists.mapfoldl/3
```

This seems to be an incompatibility between erl/otp 21 and elixir 1.6, my page_view.ex is the standard, no modification on any of these files in my app - I'm still using Phoenix 1.3, and want to use it - but don't know which other container of yours I should switch to? I assume it's just bad versioning from erlang solutions with their `https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb` package. Since it downloads the latest erlang version, and this is in your Dockerfile.

**Comment by bitwalker** [comment]
You can definitely use Phoenix 1.3 with the latest image (which in a few minutes here will be 1.8.1 with the latest Erlang). You may get some compiler warnings, but everything will still work (I have an older Phoenix project laying around that still builds with the latest).

1.7.3 was originally tagged/released with OTP 21 IIRC, so I don't know why you would be getting something incompatible at this point, but I think I do recall there being some OTP bug, and perhaps the version you have is not a point release containing the fix. This image doesn't install Erlang though (that comes from `alpine-erlang`), so you could always rebuild this image locally using an older version of `alpine-elixir` based on an older version of `alpine-erlang`. 

In general the images I provide are mostly about the Dockerfiles themselves, and less about having them published to Docker Hub, though I do regularly push out updates; I just don't make guarantees about older versions, since I don't have the time to maintain the exponential number of variations that are possible, so I can only really make sure the latest versions are stable. As a rule I don't overwrite pre-existing tags, with the exception of releases which are the latest versions of "rollup" tags, i.e. `alpine-elixir:1` or `alpine-elixir:1.8` which should always point to the latest 1.x or 1.8.x release respectively.

Hope that answers your question, sorry for the trouble!
